name: Ruby and other things!
highlighter: rouge
exclude: ["vendor", "Gemfile", "Gemfile.lock", "Procfile", "README.md", '404.html']
url: http://markcampbell.me
markdown: kramdown
kramdown:
  input: GFM
